server:
  port: 8444
pageController:
  msg: "Hello from application YAML"

my:
  secret: ${random.value}
  number: ${random.int}  
app:
  name: My cool Application
  description: ${app.name} is a Spring Boot App [Delelopment ENV]
  
emailconfig:
  from: test-dev@test.com
  to: destiny-dev@dest.com
  subject: test message from development env
  content-type: plain text
  

